---

- name: install human tools
  become: true
  yum:
    name: 
      - emacs-nox
      - htop
      - lsof
      - mlocate
      - strace
      - tmux
    state: present

- name: get team public keys
  git: repo=https://github.com/mozilla/identity-pubkeys.git
       dest=/home/ec2-user/identity-pubkeys
       version=faf11d61fdc166004c134b75587d059734f5bdb1
       force=true
  notify: update authorized_keys
