---

- name: install redis
  become: true
  yum: 
    name: redis
    state: present 
    enablerepo: epel

- name: start redis
  become: true
  service: name=redis enabled=yes state=started

- meta: flush_handlers
